### ISSUE TITLE
Not working since last kernel update

### ISSUE THREAD

**Issue by Dazag** [jeremyb31/newbtfix-4.15#1]
Hi, good morning! I have used this fix previously to solve my Bluetooth problems. But after the last kernel update it did stop working again... and after I applied this fix again and rebooted, nothing did change... well yes, now I can switch it on, but after a few seconds goes from searching devices to no Bluetooth device found "insert a Bluetooth dongle..." and after a few seconds again back to powered off Bluetooth device... 
Am I the only one :)

**Comment by jeremyb31** [comment]
Post results for 
`uname -a; dmesg | egrep -i 'blue|firm'; modinfo btusb | egrep 'filename|vermagic|version'`

**Comment by Dazag** [comment]
[Is this right?](https://pastebin.com/LC74zPuu) Thanks @jeremyb31

**Comment by jeremyb31** [comment]
You have Intel Bluetooth and this fix is for Atheros Bluetooth devices with ID of 0cf3:3004

**Comment by Dazag** [comment]
Thank you @jeremyb31 it seems I am more lost than I thought! thank you for your time and my apologies too.
